language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abaams78/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abaams78/docker-react npm run test

  deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "docker-env"
    bucket_name: "elasticbeanstack-us-west-2"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY